version: '3'
services:
  db:
    build: ./mysql
    container_name: db
    restart: always
    expose:
      - "3306"
    volumes:
      - dbdata:/var/lib/mysql
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    #PORTS defines ports reachable from the outside world, like a browser or other clients
    ports: 
      - "8000:8000"
      - "8001:8001"
volumes:
  dbdata: